
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/syb/Downloads/project/Log_Analysis_AI_Assistant/sample_logs/*.log
  fields:
    log_type: test
  fields_under_root: true
  # 多行合并：以 ISO 时间戳开头的行作为新事件开始
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

output.kafka:
  hosts: ["localhost:9092"]
  topic: "logs_raw"
  required_acks: 1
  compression: gzip

path.data: /home/syb/Downloads/project/Log_Analysis_AI_Assistant/filebeat_data
logging.level: info
