filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - tests/collectors/sample_logs/*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true

output.kafka:
  hosts: ["localhost:9092"]
  topic: "logs_raw"
  compression: gzip
  required_acks: 1
  max_retries: 3
